remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

title: "Raphaël Urfin - PhD Student"
name: "Raphaël Urfin"
description: "PhD Student in Machine Learning and Statistical Physics"
url: "https://urfin-raphael.github.io"
baseurl: ""
repository: "URFIN-Raphael/URFIN-Raphael.github.io"

author:
  name: "Raphaël Urfin"
  avatar: "/assets/images/profile.png"
  bio: "PhD Student in Machine Learning and Statistical Physics at ENS-PSL"
  location: "Paris, France"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=j7IYAOIAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/URFIN-Raphael"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache

navigation: main


