source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "minimal-mistakes-jekyll"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-include-cache"
gem "kramdown-parser-gfm"
