name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # 3️⃣ Install Jekyll dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 4️⃣ Build the site
      - name: Build Jekyll site
        run: bundle exec jekyll build -d ./_site

      # 5️⃣ Upload _site as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact-name: github-pages


