name: GitHub Pages

on:
  push:
    branches:
      - master   # or 'master' if your default branch is master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: _site
